#!/bin/bash

kon="t"

while [ "$kon" = "t" ]
do
                echo "Podaj imie:"
                read imie
                echo "Podaj nazwisko:"
                read nazwisko
                echo "Podaj telefon:"
                read telefon

        echo "$imie $nazwisko $telefon" >> dane.txt
        echo "Dane zostaly wczytane"
        echo "Czy chcesz kontynuowac? (t/n)"
        read kon
done

